name: Release Addon
on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0, v1.1, etc.

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package Addon
        run: |
          zip -r owen-wilson-loot-${{ github.ref_name }}.zip . -x "*.git*"
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }} of Owen Wilson Loot"
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./owen-wilson-loot-${{ github.ref_name }}.zip
          asset_name: owen-wilson-loot-${{ github.ref_name }}.zip
          asset_content_type: application/zip
